-- Add QuizzaBoom offer (shares darts_pixels lane for conflict management)

INSERT INTO offers (slug, title, description, short_desc, duration_minutes, min_players, max_players, lane_type, includes, age_min, sort_order, is_active)
VALUES (
  'quizzaboom-1h',
  '{"en": "QuizzaBoom – 1h", "es": "QuizzaBoom – 1h", "fr": "QuizzaBoom – 1h", "de": "QuizzaBoom – 1h", "nl": "QuizzaBoom – 1h"}',
  '{"en": "1-hour AI-powered interactive quiz experience! Join via QR code on your phone, answer questions on the big screen, use strategic jokers, and compete with up to 6 players. Unique questions generated by AI every game — no two sessions are alike!", "es": "1 hora de quiz interactivo con IA! Unete escaneando un codigo QR, responde en la pantalla grande, usa comodines estrategicos y compite con hasta 6 jugadores. Preguntas unicas generadas por IA en cada partida!", "fr": "1 heure de quiz interactif propulse par l''IA ! Rejoignez via QR code sur votre telephone, repondez sur grand ecran, utilisez des jokers strategiques et affrontez jusqu''a 6 joueurs. Questions uniques generees par IA a chaque partie !", "de": "1 Stunde KI-gesteuertes interaktives Quiz-Erlebnis! Per QR-Code auf dem Handy beitreten, auf dem Grossbildschirm antworten, strategische Joker einsetzen und mit bis zu 6 Spielern antreten. Einzigartige KI-generierte Fragen bei jedem Spiel!", "nl": "1 uur AI-aangedreven interactieve quiz! Doe mee via QR-code op je telefoon, beantwoord vragen op het grote scherm, gebruik strategische jokers en strijd met tot 6 spelers. Unieke AI-gegenereerde vragen bij elk spel!"}',
  '{"en": "1h AI-powered quiz game", "es": "1h juego de quiz con IA", "fr": "1h jeu de quiz propulse par l''IA", "de": "1h KI-gesteuertes Quizspiel", "nl": "1h AI-aangedreven quizspel"}',
  60, 2, 6, 'darts_pixels', '[]', 6, 11, true
);

-- Pricing: degressive per player
-- 2 players: 28€ (14€/pp), 3-4: 13€/pp, 5-6: 12€/pp
INSERT INTO offer_pricing (offer_id, players, price_cents)
SELECT id, unnest(array[2,3,4,5,6]), unnest(array[2800,3900,5200,6000,7200])
FROM offers WHERE slug = 'quizzaboom-1h';
